### ISSUE TITLE
Collaborator Sign-up

### ISSUE THREAD

**Issue by Lupus590** [CC-Hive/Main#1]
~~Please comment with what team you will be joining (or creating)~~

Teams are out, we are too small for it to be worth the effort of managing teams.

Instead, say hello and maybe what you would like to work on.

**Comment by SquidDev** [comment]
@SquidDev. Though by commenting are we not posting our name?

**Comment by Lupus590** [comment]
@SquidDev  Changed it

**Comment by 1wsx10** [comment]
the path-finding/mapping team...

that is if i can get this licensing thing worked out

**Comment by Lupus590** [comment]
@1wsx10 this is a good resource: http://choosealicense.com/

**Comment by caramelpony** [comment]
I would like to join/create the Automated Co-Operation Team. Said team is responsible for coding the API responsible for inter-turtle communications.

**Comment by Lupus590** [comment]
@TripyVOX Turtles don't need to communicate together without the server just yet, cooperative tasks are an extended goal.

I can add you to the networking team though, they handle server-turtle interaction.

**Comment by Cing2** [comment]
Testing amd debugging team

**Comment by Lupus590** [comment]
I've changed this yet again, see OP for details.

**Comment by Lupus590** [comment]
Please say hello via gitter [![Join the chat at https://gitter.im/CC-Hive/Main](https://badges.gitter.im/CC-Hive/Main.svg)](https://gitter.im/CC-Hive/Main?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
