### ISSUE TITLE
GitHub organisation needs image/logo

### ISSUE THREAD

**Issue by Lupus590** [CC-Hive/Main#5]
Preferably something which can also be rendered on a Pre-1.8 CC terminal.
This logo will be used in the project, on an about page. If we have loading times then it can go on the loading screen too.

**Comment by Lupus590** [comment]
@CC-Hive/repo-mantainance Thoughts?

```
4444444
1111111
4444444
1111111
444f444
```

![untitled](https://cloud.githubusercontent.com/assets/9790321/13551018/4e5f7882-e323-11e5-8640-89cb86c456a3.png)

http://www.computercraft.info/forums2/index.php?/topic/22421-

**Comment by 1wsx10** [comment]
looks ok

(Edit: removed email junk - @Lupus590)
